### ISSUE TITLE
logger error

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/hpoannotqc#24]
java -Xmx1G -jar jar/HpoAnnotQc.jar big-file --orphadata "data/en_product4_HPO.xml"  --hpo "data/hp.obo" --small-files "../annotated/" --out "phenotype.hpoa"
log4j:WARN No appenders could be found for logger (org.monarchinitiative.phenol.io.obo.hpo.HpOboParser).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" org.monarchinitiative.phenol.base.PhenolRuntimeException: TermId construction error: '' does not have a prefix!
	at org.monarchinitiative.phenol.ontology.data.TermId.findPrefixSeparatorPosition(TermId.java:43)
	at org.monarchinitiative.phenol.ontology.data.TermId.of(TermId.java:30)
	at org.monarchinitiative.hpoannotqc.io.SmallFileParser.parse(SmallFileParser.java:77)
	at org.monarchinitiative.hpoannotqc.io.SmallFileIngestor.inputV2files(SmallFileIngestor.java:60)
	at org.monarchinitiative.hpoannotqc.io.SmallFileIngestor.<init>(SmallFileIngestor.java:49)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:67)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:24)
makefile:44: recipe for target 'generate-annotation-file' failed
make: *** [generate-annotation-file] Error 1
make: Leaving directory '/var/lib/jenkins/jobs/hpo.annotations.2018/workspace/misc_2018'
Build step 'Execute shell' marked build as failure
Archiving artifacts
Sending e-mails to: sebastian.koehler@charite.de peter.robinson@jax.org
Finished: FAILURE

**Comment by pnrobinson** [comment]
this seems to be solved.
