### ISSUE TITLE
Orpha XML parse error

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/hpoannotqc#63]
```
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[3102,13]
Message: The element type "HPODisorderAssociation" must be terminated by the matching end-tag "</HPODisorderAssociation>".
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
	at java.xml/com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
	at org.monarchinitiative.hpoannotqc.annotations.OrphanetXML2HpoDiseaseModelParser.parse(OrphanetXML2HpoDiseaseModelParser.java:219)
	at org.monarchinitiative.hpoannotqc.annotations.OrphanetXML2HpoDiseaseModelParser.<init>(OrphanetXML2HpoDiseaseModelParser.java:150)
```

**Comment by pnrobinson** [comment]
This was do to an incomplete download of the XML file. It would be good to improve the error message.
